import type { SavedState } from './serializer';

export interface Example {
  id: string;
  name: string;
  description: string;
  state: SavedState;
}

export const EXAMPLES: Example[] = [
  {
    id: 'single-cstr',
    name: 'Single CSTR',
    description: '1st-order, isothermal \u00b7 Feed \u2192 CSTR \u2192 Product',
    state: {
      version: 1,
      nodes: [
        {
          id: 'feed',
          type: 'feed',
          position: { x: 100, y: 200 },
          data: { label: 'Feed' },
        },
        {
          id: 'cstr-2',
          type: 'cstr',
          position: { x: 300, y: 200 },
          data: {
            reactorType: 'CSTR',
            label: 'CSTR-2',
            tau: 2.0,
            thermalMode: 'isothermal',
            Tc: 300,
            kappa_v: 0.5,
            ic_Ca: 1.0,
            ic_T: 300,
          },
        },
        {
          id: 'product',
          type: 'product',
          position: { x: 520, y: 200 },
          data: { label: 'Product' },
        },
      ],
      edges: [
        { id: 'e-feed-cstr2', source: 'feed', target: 'cstr-2' },
        { id: 'e-cstr2-product', source: 'cstr-2', target: 'product' },
      ],
      params: {
        reactionMode: 'single',
        kinetics: 'first-order',
        k: 0.5,
        k2: 0.3,
        Keq_ref: 4.0,
        Ca0: 1.0,
        Cr0_fraction: 0.01,
        T_ref: 300,
        Ea: 0,
        delta_H: -50,
        rho_Cp: 4.18,
        T_feed: 300,
        epsilon: 0,
        Q_feed: 0,
        customReaction: null,
      },
      mode: 'steady-state',
    },
  },
  {
    id: 'two-cstr-series',
    name: 'Two CSTRs in Series',
    description: '1st-order, isothermal \u00b7 higher conversion through staging',
    state: {
      version: 1,
      nodes: [
        {
          id: 'feed',
          type: 'feed',
          position: { x: 100, y: 200 },
          data: { label: 'Feed' },
        },
        {
          id: 'cstr-2',
          type: 'cstr',
          position: { x: 300, y: 200 },
          data: {
            reactorType: 'CSTR',
            label: 'CSTR-2',
            tau: 2.0,
            thermalMode: 'isothermal',
            Tc: 300,
            kappa_v: 0.5,
            ic_Ca: 1.0,
            ic_T: 300,
          },
        },
        {
          id: 'cstr-3',
          type: 'cstr',
          position: { x: 500, y: 200 },
          data: {
            reactorType: 'CSTR',
            label: 'CSTR-3',
            tau: 2.0,
            thermalMode: 'isothermal',
            Tc: 300,
            kappa_v: 0.5,
            ic_Ca: 1.0,
            ic_T: 300,
          },
        },
        {
          id: 'product',
          type: 'product',
          position: { x: 720, y: 200 },
          data: { label: 'Product' },
        },
      ],
      edges: [
        { id: 'e-feed-cstr2', source: 'feed', target: 'cstr-2' },
        { id: 'e-cstr2-cstr3', source: 'cstr-2', target: 'cstr-3' },
        { id: 'e-cstr3-product', source: 'cstr-3', target: 'product' },
      ],
      params: {
        reactionMode: 'single',
        kinetics: 'first-order',
        k: 0.3,
        k2: 0.3,
        Keq_ref: 4.0,
        Ca0: 1.0,
        Cr0_fraction: 0.01,
        T_ref: 300,
        Ea: 0,
        delta_H: -50,
        rho_Cp: 4.18,
        T_feed: 300,
        epsilon: 0,
        Q_feed: 0,
        customReaction: null,
      },
      mode: 'steady-state',
    },
  },
  {
    id: 'cstr-pfr',
    name: 'CSTR + PFR',
    description: '2nd-order, isothermal \u00b7 hybrid design',
    state: {
      version: 1,
      nodes: [
        {
          id: 'feed',
          type: 'feed',
          position: { x: 100, y: 200 },
          data: { label: 'Feed' },
        },
        {
          id: 'cstr-2',
          type: 'cstr',
          position: { x: 300, y: 200 },
          data: {
            reactorType: 'CSTR',
            label: 'CSTR-2',
            tau: 2.0,
            thermalMode: 'isothermal',
            Tc: 300,
            kappa_v: 0.5,
            ic_Ca: 1.0,
            ic_T: 300,
          },
        },
        {
          id: 'pfr-2',
          type: 'pfr',
          position: { x: 520, y: 200 },
          data: {
            reactorType: 'PFR',
            label: 'PFR-2',
            tau: 4.0,
            thermalMode: 'isothermal',
            Tc: 300,
            kappa_v: 0.5,
            ic_Ca: 1.0,
            ic_T: 300,
          },
        },
        {
          id: 'product',
          type: 'product',
          position: { x: 740, y: 200 },
          data: { label: 'Product' },
        },
      ],
      edges: [
        { id: 'e-feed-cstr2', source: 'feed', target: 'cstr-2' },
        { id: 'e-cstr2-pfr2', source: 'cstr-2', target: 'pfr-2' },
        { id: 'e-pfr2-product', source: 'pfr-2', target: 'product' },
      ],
      params: {
        reactionMode: 'single',
        kinetics: 'second-order',
        k: 0.4,
        k2: 0.3,
        Keq_ref: 4.0,
        Ca0: 1.0,
        Cr0_fraction: 0.01,
        T_ref: 300,
        Ea: 0,
        delta_H: -50,
        rho_Cp: 4.18,
        T_feed: 300,
        epsilon: 0,
        Q_feed: 0,
        customReaction: null,
      },
      mode: 'steady-state',
    },
  },

  {
    id: 'recycle-pfr',
    name: 'Recycle Reactor',
    description: 'PFR + 50% recycle \u00b7 approaches CSTR at high recycle ratio',
    state: {
      version: 1,
      nodes: [
        { id: 'feed', type: 'feed', position: { x: 60, y: 230 }, data: { label: 'Feed' } },
        { id: 'mixer-1', type: 'mixer', position: { x: 220, y: 220 }, data: { label: 'Mixer-1' } },
        {
          id: 'pfr-2', type: 'pfr', position: { x: 400, y: 220 },
          data: { reactorType: 'PFR', label: 'PFR-2', tau: 3.0, thermalMode: 'isothermal', Tc: 300, kappa_v: 0.5, ic_Ca: 1.0, ic_T: 300 },
        },
        { id: 'splitter-1', type: 'splitter', position: { x: 610, y: 220 }, data: { label: 'Split-1', alpha: 0.5 } },
        { id: 'product', type: 'product', position: { x: 790, y: 230 }, data: { label: 'Product' } },
      ],
      edges: [
        { id: 'e-feed-mix',    source: 'feed',      target: 'mixer-1'   },
        { id: 'e-mix-pfr',     source: 'mixer-1',   target: 'pfr-2'     },
        { id: 'e-pfr-spl',     source: 'pfr-2',     target: 'splitter-1' },
        { id: 'e-spl-prod',    source: 'splitter-1', target: 'product'  },
        { id: 'e-spl-recycle', source: 'splitter-1', target: 'mixer-1'  },
      ],
      params: {
        reactionMode: 'single',
        kinetics: 'first-order',
        k: 0.5,
        k2: 0.3,
        Keq_ref: 4.0,
        Ca0: 1.0,
        Cr0_fraction: 0.01,
        T_ref: 300,
        Ea: 0,
        delta_H: -50,
        rho_Cp: 4.18,
        T_feed: 300,
        epsilon: 0,
        Q_feed: 0,
        customReaction: null,
      },
      mode: 'steady-state',
    },
  },

  {
    id: 'adiabatic-cstr-chain',
    name: 'Adiabatic CSTR Chain',
    description: '3 adiabatic CSTRs \u00b7 temperature staging \u00b7 Ea=60 kJ/mol',
    state: {
      version: 1,
      nodes: [
        { id: 'feed', type: 'feed', position: { x: 60, y: 230 }, data: { label: 'Feed' } },
        {
          id: 'cstr-2', type: 'cstr', position: { x: 230, y: 220 },
          data: { reactorType: 'CSTR', label: 'CSTR-2', tau: 2.0, thermalMode: 'adiabatic', Tc: 300, kappa_v: 0.5, ic_Ca: 1.0, ic_T: 300 },
        },
        {
          id: 'cstr-3', type: 'cstr', position: { x: 450, y: 220 },
          data: { reactorType: 'CSTR', label: 'CSTR-3', tau: 2.0, thermalMode: 'adiabatic', Tc: 300, kappa_v: 0.5, ic_Ca: 1.0, ic_T: 300 },
        },
        {
          id: 'cstr-4', type: 'cstr', position: { x: 670, y: 220 },
          data: { reactorType: 'CSTR', label: 'CSTR-4', tau: 2.0, thermalMode: 'adiabatic', Tc: 300, kappa_v: 0.5, ic_Ca: 1.0, ic_T: 300 },
        },
        { id: 'product', type: 'product', position: { x: 890, y: 230 }, data: { label: 'Product' } },
      ],
      edges: [
        { id: 'e-feed-c2',  source: 'feed',   target: 'cstr-2' },
        { id: 'e-c2-c3',    source: 'cstr-2', target: 'cstr-3' },
        { id: 'e-c3-c4',    source: 'cstr-3', target: 'cstr-4' },
        { id: 'e-c4-prod',  source: 'cstr-4', target: 'product' },
      ],
      params: {
        reactionMode: 'single',
        kinetics: 'first-order',
        k: 0.1,
        k2: 0.3,
        Keq_ref: 4.0,
        Ca0: 1.0,
        Cr0_fraction: 0.01,
        T_ref: 300,
        Ea: 60,
        delta_H: -100,
        rho_Cp: 1.0,
        T_feed: 300,
        epsilon: 0,
        Q_feed: 0,
        customReaction: null,
      },
      mode: 'steady-state',
    },
  },

  {
    id: 'series-intermediate',
    name: 'Series Intermediate A\u2192R\u2192S',
    description: 'CSTR \u2192 PFR \u00b7 series kinetics \u00b7 C\u1d38 maximum at Da\u2092\u209a\u209c',
    state: {
      version: 1,
      nodes: [
        { id: 'feed', type: 'feed', position: { x: 100, y: 200 }, data: { label: 'Feed' } },
        {
          id: 'cstr-2', type: 'cstr', position: { x: 300, y: 200 },
          data: { reactorType: 'CSTR', label: 'CSTR-2', tau: 2.0, thermalMode: 'isothermal', Tc: 300, kappa_v: 0.5, ic_Ca: 1.0, ic_T: 300 },
        },
        {
          id: 'pfr-2', type: 'pfr', position: { x: 520, y: 200 },
          data: { reactorType: 'PFR', label: 'PFR-2', tau: 4.0, thermalMode: 'isothermal', Tc: 300, kappa_v: 0.5, ic_Ca: 1.0, ic_T: 300 },
        },
        { id: 'product', type: 'product', position: { x: 740, y: 200 }, data: { label: 'Product' } },
      ],
      edges: [
        { id: 'e-feed-c2',   source: 'feed',   target: 'cstr-2' },
        { id: 'e-c2-pfr2',   source: 'cstr-2', target: 'pfr-2'  },
        { id: 'e-pfr2-prod', source: 'pfr-2',  target: 'product' },
      ],
      params: {
        reactionMode: 'series',
        kinetics: 'first-order',
        k: 0.5,
        k2: 0.1,
        Keq_ref: 4.0,
        Ca0: 1.0,
        Cr0_fraction: 0.01,
        T_ref: 300,
        Ea: 0,
        delta_H: -50,
        rho_Cp: 4.18,
        T_feed: 300,
        epsilon: 0,
        Q_feed: 0,
        customReaction: null,
      },
      mode: 'steady-state',
    },
  },

  {
    id: 'gas-phase-expansion',
    name: 'Gas-Phase Expansion',
    description: 'Isothermal PFR \u00b7 \u03b5=0.5 \u00b7 volumetric expansion reduces conversion',
    state: {
      version: 1,
      nodes: [
        { id: 'feed', type: 'feed', position: { x: 100, y: 230 }, data: { label: 'Feed' } },
        {
          id: 'pfr-2', type: 'pfr', position: { x: 320, y: 220 },
          data: { reactorType: 'PFR', label: 'PFR-2', tau: 3.0, thermalMode: 'isothermal', Tc: 300, kappa_v: 0.5, ic_Ca: 0.5, ic_T: 300 },
        },
        { id: 'product', type: 'product', position: { x: 560, y: 230 }, data: { label: 'Product' } },
      ],
      edges: [
        { id: 'e-feed-pfr', source: 'feed',  target: 'pfr-2'  },
        { id: 'e-pfr-prod', source: 'pfr-2', target: 'product' },
      ],
      params: {
        reactionMode: 'single',
        kinetics: 'first-order',
        k: 0.3,
        k2: 0.3,
        Keq_ref: 4.0,
        Ca0: 0.5,
        Cr0_fraction: 0.01,
        T_ref: 300,
        Ea: 0,
        delta_H: -50,
        rho_Cp: 4.18,
        T_feed: 300,
        epsilon: 0.5,
        Q_feed: 0,
        customReaction: null,
      },
      mode: 'steady-state',
    },
  },

  {
    id: 'parallel-split',
    name: 'Optimal Parallel Split',
    description: 'Splitter \u2192 [CSTR \u2225 PFR] \u2192 Mixer \u00b7 intermediate conversion between extremes',
    state: {
      version: 1,
      nodes: [
        { id: 'feed', type: 'feed', position: { x: 60, y: 230 }, data: { label: 'Feed' } },
        { id: 'splitter-1', type: 'splitter', position: { x: 220, y: 230 }, data: { label: 'Split-1', alpha: 0.5 } },
        {
          id: 'cstr-2', type: 'cstr', position: { x: 420, y: 130 },
          data: { reactorType: 'CSTR', label: 'CSTR-2', tau: 2.0, thermalMode: 'isothermal', Tc: 300, kappa_v: 0.5, ic_Ca: 1.0, ic_T: 300 },
        },
        {
          id: 'pfr-2', type: 'pfr', position: { x: 420, y: 310 },
          data: { reactorType: 'PFR', label: 'PFR-2', tau: 2.0, thermalMode: 'isothermal', Tc: 300, kappa_v: 0.5, ic_Ca: 1.0, ic_T: 300 },
        },
        { id: 'mixer-1', type: 'mixer', position: { x: 650, y: 230 }, data: { label: 'Mixer-1' } },
        { id: 'product', type: 'product', position: { x: 830, y: 230 }, data: { label: 'Product' } },
      ],
      edges: [
        { id: 'e-feed-spl',  source: 'feed',      target: 'splitter-1' },
        { id: 'e-spl-cstr',  source: 'splitter-1', target: 'cstr-2'   },
        { id: 'e-spl-pfr',   source: 'splitter-1', target: 'pfr-2'    },
        { id: 'e-cstr-mix',  source: 'cstr-2',    target: 'mixer-1'   },
        { id: 'e-pfr-mix',   source: 'pfr-2',     target: 'mixer-1'   },
        { id: 'e-mix-prod',  source: 'mixer-1',   target: 'product'   },
      ],
      params: {
        reactionMode: 'single',
        kinetics: 'first-order',
        k: 0.5,
        k2: 0.3,
        Keq_ref: 4.0,
        Ca0: 1.0,
        Cr0_fraction: 0.01,
        T_ref: 300,
        Ea: 0,
        delta_H: -50,
        rho_Cp: 4.18,
        T_feed: 300,
        epsilon: 0,
        Q_feed: 0,
        customReaction: null,
      },
      mode: 'steady-state',
    },
  },
];
