name: Deploy to Vercel

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      - run: npx vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: team_Ah5Vpwjd9Vkb0e4jqEICY0WI
          VERCEL_PROJECT_ID: prj_bqvF7AlBOTw67zMeqwBCPjLDvBF3

      - run: npx vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: team_Ah5Vpwjd9Vkb0e4jqEICY0WI
          VERCEL_PROJECT_ID: prj_bqvF7AlBOTw67zMeqwBCPjLDvBF3

      - run: npx vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: team_Ah5Vpwjd9Vkb0e4jqEICY0WI
          VERCEL_PROJECT_ID: prj_bqvF7AlBOTw67zMeqwBCPjLDvBF3
